#
# - 업데이트 일자 : 2025-09-08
# - 연동 기술지원 연락처 : 1600-9854
# - 연동 기술지원 이메일 : code@linkhubcorp.com
#
# <테스트 연동개발 준비사항>
#   1) API Key 변경 (연동신청 시 메일로 전달된 정보)
#       - LinkID : 링크허브에서 발급한 링크아이디
#       - SecretKey : 링크허브에서 발급한 비밀키
#   2) ClientCode 변경 (연동신청 시 메일로 전달된 정보)
#       - ClientCode : 이용기관코드 (파트너 사이트에서 확인가능)
#   3) SDK 환경설정 필수 옵션 설정
#       - IPRestrictOnOff : 인증토큰 IP 검증 설정, true-사용, false-미사용, (기본값:true)
#       - UseStaticIP : 통신 IP 고정, true-사용, false-미사용, (기본값:false)
#

kakaocert:
  # 링크아이디
  linkId: TESTER
  # 비밀키
  secretKey: SwWxqU+0TErBXy/9TVjIPEnI0VTUMMSQZtJf3Ed8q3I=
  # 이용기관코드 (파트너 사이트에서 확인가능)
  clientCode: '023040000001'
  # 인증토큰 IP 검증 설정, true-사용, false-미사용, (기본값:true)
  isIpRestrictOnOff: true
  # 통신 IP 고정, true-사용, false-미사용, (기본값:false)
  useStaticIp: false

navercert:
  # 링크아이디
  linkId: TESTER
  # 비밀키
  secretKey: SwWxqU+0TErBXy/9TVjIPEnI0VTUMMSQZtJf3Ed8q3I=
  # 이용기관코드 (파트너 사이트에서 확인가능)
  clientCode: '023090000021'
  # 인증토큰 IP 검증 설정, true-사용, false-미사용, (기본값:true)
  isIpRestrictOnOff: true
  # 통신 IP 고정, true-사용, false-미사용, (기본값:false)
  useStaticIp: false

passcert:
  # 링크아이디
  linkId: TESTER
  # 비밀키
  secretKey: SwWxqU+0TErBXy/9TVjIPEnI0VTUMMSQZtJf3Ed8q3I=
  # 이용기관코드 (파트너 사이트에서 확인가능)
  clientCode: '023070000014'
  # 인증토큰 IP 검증 설정, true-사용, false-미사용, (기본값:true)
  isIpRestrictOnOff: true
  # 통신 IP 고정, true-사용, false-미사용, (기본값:false)
  useStaticIp: false
  
  
spring:
  thymeleaf:
    cache: false

server:
  port: 10002
